### ISSUE TITLE
Git client

### ISSUE THREAD

**Issue by veropolar** [UM-R-for-EnvSci-Auditor/General-Discussion#1]
@peperg  How much are we going to work with Git? Would you recommend to install a Git client? Thank you

**Comment by peperg** [comment]
@veropolar We will be using it mainly as a way of sharing class code and assignments. For this course, the easiest is just to use the integrated Git client capabilities in RStudio. So no other client needed for this course. Of course, if you already have one you use, and are comfortable with, fee free to use it!
