### ISSUE TITLE
Session -> Restart R and Ctrl + Shift + Fn + F10 does not clean Environment

### ISSUE THREAD

**Issue by veropolar** [UM-R-for-EnvSci-Auditor/General-Discussion#2]
Hey Pepe, 
I was wondering if you know why my Rstudio does not clean the Environment when I restart an R session (either clicking on Session -> Restart R or using the keyboard shortcut, same outcome). 
When I do that, the Console tells me "Restarting R session" as normal, then it clears the Environment for like 2 secs and then all the previous variables reappear in the Environment. 
Just wondering if this has happened to you/others before? Thank you

**Comment by peperg** [comment]
Veronica,

The only reason i can think of is that you still have the RStudio preferences set to save and restore the .RData on startup.

My recommendation is to set it up to never save the workspace and to not restore the .RData on startup. 

Below are my settings.

Let me know if this is the issue.

Pepe

<img width="446" alt="Screen Shot 2020-10-05 at 10 46 17 AM copy" src="https://user-images.githubusercontent.com/35853590/95102072-89e3dd00-06f8-11eb-9a11-d97d64a44a83.png">

**Comment by veropolar** [comment]
Hi Pepe,
Thank you for your reply.

I agree, I thought the same, so I checked it again, but to luck. It was already set like yours.

Ok, thank you anyway, I will just dig a bit more into the Internet, maybe somebody had the same issue!

Best,
Veronica

___________________________________________

Veronica Coppolaro
PhD Student
Centre for Earth Observation Science (CEOS)
Arctic Science Partnership (ASP)
463 Wallace Building
125 Dysart Road
University of Manitoba
Winnipeg, MB          R3T 2N2

________________________________

**Comment by peperg** [comment]
hummmmmm... That is weird! I cannot think of a different reason right now. 

I will see if i can find an alternate explanation. If you do find one, please share!

**Comment by peperg** [comment]
Did you figure out why it wasn't working? I'm quite curious!

**Comment by veropolar** [comment]
Soooo! I found the bug. I actually had the "Save workspace to .RData on exit" dropdown option on "Ask", which I assumed would ask before closing, no? Instead, it doesn't!
Apparently, RStudio needs to have "Never" (like you have set) to clean the environment when restarting the R session for real, because somehow (I don't know why) the environment is temporarily saved somewhere and when you use the shortcut Ctrl + (...)  it does not ask and reloads it automatically.

**Comment by peperg** [comment]
Interesting... Good to know, i would have figured, as well, that it would ask on any instance, but it seems that it only asks when you actually try to close, not on restart. Something to keep in mind! Glad you figures it out!
